export const chapter = {
  id: 'grand-opening-v1', title: 'The Grand Opening',
  subtitle: 'Nine small mysteries. One very big mistake.',
  scenes: [
    { id:'pot', title:'Before the doors open', place:'The stove', level:1,
      answer:'a watched pot never boils', aliases:['watched pot never boils','the watched pot never boils'],
      lead:'The first cook has one job: get dinner started.',
      description:'A cook watches a pot intently. It stays still while watched; when the cook looks away, the water bubbles. The pattern repeats.',
      hints:[{id:'eyes',label:'Watch the cook',x:29,y:33,text:'Notice the difference between looking at the pot and looking away.',letter:'W',focus:'eyes'}, {id:'water',label:'Inspect the water',x:64,y:58,text:'The bubbles only appear when nobody is watching.',letter:'B',focus:'water'}],
      explain:'The pot refuses to boil while the cook watches. It starts bubbling the moment the cook looks away.',
      evidence:'Cook 01 · An impatient start', bridge:'A second cook arrives to handle the service.' },
    { id:'plates', title:'A balancing problem', place:'The service counter', level:1,
      answer:'keep the plates spinning', aliases:['keep plates spinning','keeping the plates spinning','keeping plates spinning','spinning plates','keep all the plates spinning'],
      lead:'Service is not open yet, but one cook is already juggling jobs.',
      description:'Three plates spin on narrow poles. A cook rushes from one slowing, wobbling plate to the next, spinning each again before it falls.',
      hints:[{id:'plates',label:'Watch the plates',x:48,y:27,text:'Each plate wobbles as it slows. The cook must keep all three moving.',letter:'P',focus:'plates'}, {id:'hands',label:'Follow the cook',x:65,y:59,text:'One task cannot be left alone while the other tasks are being handled.',letter:'S',focus:'hands'}],
      explain:'The cook keeps several plates spinning at once, like keeping several tasks going.',
      evidence:'Cook 02 · Too many tasks', bridge:'Outside, a third cook discovers a very small problem.' },
    { id:'mountain', title:'A growing concern', place:'The herb garden', level:2,
      answer:'make a mountain out of a molehill', aliases:['making a mountain out of a molehill','a mountain out of a molehill'],
      lead:'The garden inspection seems to be getting out of hand.',
      description:'A mole runs out of its mound and returns. A wizard casts a spell, transforming the molehill into an enormous original armoured knight.',
      hints:[{id:'mole',label:'Read the nameplate',x:48,y:77,text:'The creature is a mole. The knight is called The Mountain. The wizard has made one out of the other.',letter:'M',focus:'mole'}, {id:'summit',label:'Look at the summit',x:57,y:29,text:'A very small problem has become a huge mountain.',letter:'O',focus:'summit'}],
      explain:'A wizard makes The Mountain, an enormous knight, out of a little molehill. The transformation illustrates an exaggerated reaction to a small problem.',
      evidence:'Cook 03 · A small problem grows', bridge:'Back inside, the next cook has a quicker way to tidy up.' },
    { id:'rug', title:'Nothing to see here', place:'The dining room', level:2,
      answer:'sweep it under the carpet', aliases:['sweep it under the rug','sweep under the carpet','sweeping it under the carpet','sweeping it under the rug','sweep things under the carpet','sweep things under the rug','sweep something under the carpet','sweep something under the rug'],
      lead:'The room needs to look spotless for the first guests.',
      description:'A cook sweeps scattered rubbish beneath the lifted edge of a carpet. The mess disappears, but a large bump grows under the carpet.',
      hints:[{id:'broom',label:'Follow the broom',x:43,y:63,text:'The rubbish is moved out of sight instead of being dealt with.',letter:'S',focus:'broom'}, {id:'rug',label:'Lift the edge',x:70,y:75,text:'The growing lump tells you exactly where the mess has gone.',letter:'C',focus:'rug'}],
      explain:'The mess is swept under a carpet: hiding a problem rather than solving it.',
      evidence:'Cook 04 · A hidden mess', bridge:'Meanwhile, the supplies budget is disappearing.' },
    { id:'drain', title:'An expensive shortcut', place:'The washing station', level:2,
      answer:'throw money down the drain', aliases:['throwing money down the drain','money down the drain','pour money down the drain','pouring money down the drain'],
      lead:'Another cook insists that spending more will fix everything.',
      description:'A cook tips a purse of gold coins over a sink. Coins spiral around the basin and vanish down its drain.',
      hints:[{id:'coins',label:'Inspect the purse',x:33,y:36,text:'The things falling from the purse are coins.',letter:'M',focus:'coins'}, {id:'drain',label:'Look into the sink',x:63,y:64,text:'The money vanishes down the drain without achieving anything.',letter:'D',focus:'drain'}],
      explain:'Money is literally being thrown down a drain: spending it wastefully.',
      evidence:'Cook 05 · The budget disappears', bridge:'The gardener decides to fix the trouble outside personally.' },
    { id:'hole', title:'Making matters worse', place:'The herb garden', level:3,
      answer:'dig yourself into a hole', aliases:['digging yourself into a hole','dig a hole for yourself','digging a hole for yourself','dig himself into a hole','digging himself into a hole'],
      lead:'Every attempted repair seems to make this job harder.',
      description:'A cook digs beneath their own feet. With each shovel of soil the hole deepens and the cook sinks lower, until only the hat is visible.',
      hints:[{id:'shovel',label:'Follow the shovel',x:40,y:47,text:'The cook is removing the ground directly beneath their own feet.',letter:'D',focus:'shovel'}, {id:'depth',label:'Check the depth',x:66,y:76,text:'Every attempt to fix the situation leaves the cook deeper in trouble.',letter:'H',focus:'depth'}],
      explain:'The cook digs themselves into an ever-deeper hole, making their own predicament worse.',
      evidence:'Cook 06 · A deeper predicament', bridge:'A crash from the kitchen brings everyone running.' },
    { id:'milk', title:'The little spill', place:'The prep table', level:3,
      answer:'cry over spilt milk', aliases:['cry over spilled milk','crying over spilt milk','crying over spilled milk','dont cry over spilt milk','dont cry over spilled milk','no use crying over spilt milk','no use crying over spilled milk'],
      lead:'There is plenty in the pantry. One cook has forgotten that.',
      description:'A milk bottle tips over and spills. A cook kneels over the white puddle crying, while a full replacement bottle stands untouched on a nearby shelf.',
      hints:[{id:'spill',label:'Inspect the puddle',x:58,y:74,text:'It is milk from the overturned bottle.',letter:'M',focus:'spill'}, {id:'tears',label:'Watch the reaction',x:31,y:46,text:'The cook is crying over something that has already happened.',letter:'C',focus:'tears'}],
      explain:'The cook cries over spilt milk, dwelling on a mishap that cannot be undone.',
      evidence:'Cook 07 · A needless fuss', bridge:'A quiet corner offers a chance to avoid another disaster.' },
    { id:'dogs', title:'Do not disturb', place:'The back entrance', level:3,
      answer:'let sleeping dogs lie', aliases:['leave sleeping dogs lie','let the sleeping dogs lie'],
      lead:'The next cook cannot resist investigating a perfectly quiet corner.',
      description:'Two dogs sleep peacefully. A cook nudges one with a spoon; both jump up barking. The cook backs away, and the dogs settle down again.',
      hints:[{id:'dogs',label:'Watch the dogs',x:65,y:71,text:'Everything is peaceful until their sleep is disturbed.',letter:'D',focus:'dogs'}, {id:'spoon',label:'Follow the spoon',x:38,y:49,text:'Leaving them alone avoids stirring up trouble.',letter:'L',focus:'spoon'}],
      explain:'Leaving sleeping dogs undisturbed avoids unnecessary trouble.',
      evidence:'Cook 08 · Trouble stirred up', bridge:'There is still one ingredient delivery to check.' },
    { id:'eggs', title:'An optimistic order', place:'The kitchen garden', level:3,
      answer:'dont count your chickens before they hatch', aliases:['do not count your chickens before they hatch','dont count your chickens before they are hatched','do not count your chickens before they are hatched','counting your chickens before they hatch','count your chickens before they hatch'],
      lead:'The last cook is already planning a feast from a promise.',
      description:'A cook counts six imagined chicks above six unhatched eggs. When the eggs begin to hatch, only two chicks appear and the imagined six disappear.',
      hints:[{id:'count',label:'Check the count',x:30,y:29,text:'The cook is counting chicks that exist only in a thought bubble.',letter:'C',focus:'count'}, {id:'eggs',label:'Inspect the eggs',x:68,y:73,text:'The eggs have not hatched yet. The expected result is not guaranteed.',letter:'H',focus:'eggs'}],
      explain:'The cook counts imagined chickens before the eggs hatch: relying on success before it happens.',
      evidence:'Cook 09 · Assumptions before results', bridge:'The camera finally pulls back. All nine cooks have one more idea…' },
    { id:'finale', title:'The bigger picture', place:'The whole kitchen', level:3, finale:true,
      answer:'too many cooks spoil the broth', aliases:['too many cooks spoil the soup','too many chefs spoil the broth','too many chefs spoil the soup'],
      lead:'Nine cooks. Nine small disasters. What phrase explains the whole opening?',
      description:'All nine cooks gather around the same soup pot, each adding their own ingredients and stirring at once. The soup turns into a lumpy mess and everyone recoils.',
      hints:[{id:'cooks',label:'Count the cooks',x:27,y:37,text:'The earlier scenes introduced nine different cooks, all taking charge.',letter:'C',focus:'cooks'}, {id:'broth',label:'Inspect the soup',x:54,y:63,text:'Their competing contributions have spoiled the same pot of broth.',letter:'B',focus:'broth'}],
      explain:'Every earlier scene introduced a different cook making their own decisions. Now all nine interfere with the same soup, spoiling it. Too many cooks spoil the broth.',
      evidence:'The whole picture · Everyone takes charge', bridge:'The opening will have to wait. At least you solved the mystery.' }
  ]
};
