(() => {
  const viewport=document.querySelector('#viewport'),scenes=[...document.querySelectorAll('.scene')],status=document.querySelector('#status'),orderScene=document.querySelector('#orderScene'),pieces=[...document.querySelectorAll('.timepiece')],sockets=[...document.querySelectorAll('.socket')],key=document.querySelector('#keyPiece'),keyhole=document.querySelector('#keyhole'),dial=document.querySelector('#dialZone'),pointer=document.querySelector('#dialPointer'),yearWindow=document.querySelector('#yearWindow'),answerLock=document.querySelector('#answerLock');
  const correctOrder=['sundial','hourglass','pocket','digital'],years=['2026','2000','1900','1000','100','1','YEAR'];
  const trayPositions={digital:[28,64],sundial:[72,64],pocket:[28,86],hourglass:[72,86]},socketPositions=[[15.5,33.5],[38.5,33.5],[61.5,33.5],[84.5,33.5]];
  const clues=['These instruments do not belong to the same age.','The rail begins with shadows and ends with digits.','Once the mechanism opens, take the years back to their first mark.'];
  let placements=[null,null,null,null],selected=null,phase='order',dialStep=0,dialDrag=null,clueIndex=0,soundOn=true,audioContext;
  const setPosition=(el,x,y)=>{el.style.left=`${x}%`;el.style.top=`${y}%`},message=text=>{status.textContent=text},tactile=(pattern=10)=>{if(navigator.vibrate)navigator.vibrate(pattern)};
  function tone(frequency=180,duration=.06,type='sine',volume=.025){if(!soundOn)return;try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type=type;oscillator.frequency.value=frequency;gain.gain.setValueAtTime(volume,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+duration);oscillator.connect(gain).connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+duration)}catch(_){}}
  function showScene(name){scenes.forEach(scene=>{const active=scene.dataset.scene===name;if(scene.classList.contains('active')&&!active)scene.classList.add('exit-left');scene.classList.toggle('active',active);scene.setAttribute('aria-hidden',String(!active))});setTimeout(()=>scenes.forEach(scene=>scene.classList.remove('exit-left')),700)}
  function clearSelection(){selected?.classList.remove('selected');selected=null;sockets.forEach(slot=>slot.classList.remove('target'));keyhole.classList.remove('ready')}
  function selectPiece(piece){document.querySelectorAll('.piece.selected').forEach(el=>el.classList.remove('selected'));selected=selected===piece?null:piece;selected?.classList.add('selected');sockets.forEach(slot=>slot.classList.toggle('target',Boolean(selected?.classList.contains('timepiece'))));if(selected===key)keyhole.classList.add('ready')}
  function freeFromSocket(piece){const index=placements.indexOf(piece.dataset.piece);if(index>=0)placements[index]=null}
  function placeInSocket(piece,index){if(phase!=='order'||!piece.classList.contains('timepiece'))return;freeFromSocket(piece);const occupant=placements[index];if(occupant){const other=pieces.find(item=>item.dataset.piece===occupant);setPosition(other,...trayPositions[occupant])}placements[index]=piece.dataset.piece;setPosition(piece,...socketPositions[index]);tone(270+index*35,.08,'triangle');tactile(8);clearSelection();if(placements.every(Boolean))setTimeout(checkOrder,330)}
  function checkOrder(){if(placements.join('|')===correctOrder.join('|')){phase='key';message('A concealed drawer releases with a heavy click.');tone(94,.35,'sawtooth',.018);tactile([15,35,15]);setTimeout(()=>{showScene('key');tone(360,.16,'triangle')},550)}else{message('The ages disagree. The rail rejects them.');tone(72,.2,'square',.016);tactile([20,35,20]);pieces.forEach(piece=>piece.classList.add('shake'));setTimeout(()=>{pieces.forEach(piece=>{piece.classList.remove('shake');setPosition(piece,...trayPositions[piece.dataset.piece])});placements=[null,null,null,null]},430)}}
  function unlockDial(){if(phase!=='key')return;phase='dial';clearSelection();message('The great dial wakes—with nowhere to go but back.');tone(130,.12,'sawtooth');tactile([12,25,12]);viewport.classList.add('glow');setTimeout(()=>{viewport.classList.remove('glow');showScene('dial');dial.classList.remove('locked');dial.tabIndex=0;dial.focus({preventScroll:true})},480)}
  const handTransform=degrees=>`rotate(${degrees}deg)`;
  function advanceDial(){if(phase!=='dial'||dialStep>=years.length-1)return;dialStep++;pointer.style.transform=handTransform(-dialStep*48);yearWindow.textContent=years[dialStep];dial.setAttribute('aria-valuenow',String(dialStep));dial.setAttribute('aria-valuetext',years[dialStep]);tone(140+dialStep*24,.07,'triangle',.035);tactile(12);if(dialStep===years.length-1)setTimeout(transformYearToDot,420)}
  function resistDial(){pointer.animate([{transform:handTransform(-dialStep*48)},{transform:handTransform(-(dialStep*48)+7)},{transform:handTransform(-dialStep*48)}],{duration:260});tone(65,.09,'square',.012);message('The mechanism resists the future.')}
  function transformYearToDot(){phase='transforming';message('The final inscription is drawn into the origin.');yearWindow.classList.add('year-to-dot');setTimeout(()=>{yearWindow.classList.remove('year-to-dot');yearWindow.textContent='•';dial.setAttribute('aria-valuetext','origin dot');viewport.classList.add('glow');setTimeout(()=>{viewport.classList.remove('glow');showScene('origin');phase='answer';message('A year has been reduced to the first dot. Name the phrase.');answerLock.hidden=false;setTimeout(()=>document.querySelector('#answerInput').focus({preventScroll:true}),500);tone(410,.22,'triangle')},450)},1380)}
  function nearestTarget(clientX,clientY,targets,maxDistance){let best=null,bestDistance=Infinity;targets.forEach((target,index)=>{const box=target.getBoundingClientRect(),distance=Math.hypot(clientX-(box.left+box.width/2),clientY-(box.top+box.height/2));if(distance<bestDistance){best={target,index};bestDistance=distance}});return bestDistance<=maxDistance?best:null}
  function installDrag(piece,container,onDrop){let drag=null;piece.addEventListener('pointerdown',event=>{if(piece.disabled)return;drag={id:event.pointerId,startX:event.clientX,startY:event.clientY,moved:false};piece.setPointerCapture(event.pointerId)});piece.addEventListener('pointermove',event=>{if(!drag||drag.id!==event.pointerId)return;if(Math.hypot(event.clientX-drag.startX,event.clientY-drag.startY)>5)drag.moved=true;if(!drag.moved)return;const box=container.getBoundingClientRect();setPosition(piece,(event.clientX-box.left)/box.width*100,(event.clientY-box.top)/box.height*100);piece.classList.add('dragging')});piece.addEventListener('pointerup',event=>{if(!drag||drag.id!==event.pointerId)return;piece.releasePointerCapture(event.pointerId);piece.classList.remove('dragging');if(!drag.moved)selectPiece(piece);else onDrop(event);drag=null});piece.addEventListener('pointercancel',()=>{piece.classList.remove('dragging');drag=null});piece.addEventListener('click',event=>{if(event.detail===0)selectPiece(piece)})}
  pieces.forEach(piece=>installDrag(piece,orderScene,event=>{const hit=nearestTarget(event.clientX,event.clientY,sockets,Math.max(52,orderScene.clientWidth*.13));if(hit)placeInSocket(piece,hit.index);else{freeFromSocket(piece);setPosition(piece,...trayPositions[piece.dataset.piece])}}));
  installDrag(key,document.querySelector('#keyScene'),event=>{const hit=nearestTarget(event.clientX,event.clientY,[keyhole],72);if(hit)unlockDial();else setPosition(key,28,66)});
  sockets.forEach((socket,index)=>socket.addEventListener('click',()=>{if(selected?.classList.contains('timepiece'))placeInSocket(selected,index)}));keyhole.addEventListener('click',()=>{if(selected===key)unlockDial()});
  const angleAt=event=>{const box=dial.getBoundingClientRect();return Math.atan2(event.clientY-(box.top+box.height/2),event.clientX-(box.left+box.width/2))*180/Math.PI};dial.addEventListener('pointerdown',event=>{if(phase!=='dial')return;dialDrag={id:event.pointerId,last:angleAt(event),ccw:0,cw:0};dial.setPointerCapture(event.pointerId)});dial.addEventListener('pointermove',event=>{if(!dialDrag||event.pointerId!==dialDrag.id)return;const next=angleAt(event);let delta=next-dialDrag.last;if(delta>180)delta-=360;if(delta< -180)delta+=360;dialDrag.last=next;if(delta<0)dialDrag.ccw+=-delta;else dialDrag.cw+=delta;if(dialDrag.ccw>=28){dialDrag.ccw=0;advanceDial()}});dial.addEventListener('pointerup',event=>{if(dialDrag?.cw>dialDrag?.ccw+18)resistDial();if(dial.hasPointerCapture(event.pointerId))dial.releasePointerCapture(event.pointerId);dialDrag=null});dial.addEventListener('keydown',event=>{if(phase!=='dial')return;if(['ArrowLeft','ArrowDown'].includes(event.key)){event.preventDefault();advanceDial()}if(['ArrowRight','ArrowUp'].includes(event.key)){event.preventDefault();resistDial()}});
  document.querySelector('#answerForm').addEventListener('submit',event=>{event.preventDefault();const input=document.querySelector('#answerInput'),feedback=document.querySelector('#answerFeedback'),guess=input.value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(guess==='the year dot'||guess==='year dot'){phase='solved';document.querySelector('#finalSeal').hidden=false;message('The cabinet opens. The phrase is solved.');tone(262,.2,'sine',.03);setTimeout(()=>tone(392,.4,'sine',.028),140);tactile([15,35,45])}else{feedback.textContent='The final lock holds. Look again at what happened to the dial.';input.select();tone(74,.12,'square',.012);tactile(18)}});
  const ledger=document.querySelector('#ledger'),clueText=document.querySelector('#clueText');function showClue(){clueText.textContent=clues[clueIndex];document.querySelector('#nextClue').hidden=clueIndex>=clues.length-1;ledger.hidden=false}document.querySelector('#clueButton').addEventListener('click',showClue);document.querySelector('#nextClue').addEventListener('click',()=>{clueIndex=Math.min(clueIndex+1,clues.length-1);showClue()});document.querySelector('#ledgerClose').addEventListener('click',()=>{ledger.hidden=true});document.querySelector('#soundButton').addEventListener('click',event=>{soundOn=!soundOn;event.currentTarget.textContent=soundOn?'Sound on':'Sound off';event.currentTarget.setAttribute('aria-pressed',String(soundOn));if(soundOn)tone(240)});document.querySelector('#resetButton').addEventListener('click',()=>window.location.reload());pieces.forEach(piece=>setPosition(piece,...trayPositions[piece.dataset.piece]));
  const previewParams=new URLSearchParams(location.search),preview=previewParams.get('preview');if(['key','dial','answer'].includes(preview)){scenes.forEach(scene=>scene.style.transition='none');phase=preview;showScene(preview==='answer'?'origin':preview);if(preview==='dial'){dial.classList.remove('locked');dial.tabIndex=0;const previewTurn=Math.max(0,Math.min(6,Number(previewParams.get('turn'))||0));dialStep=previewTurn;pointer.style.transform=handTransform(-previewTurn*48);yearWindow.textContent=years[previewTurn]}if(preview==='answer'){answerLock.hidden=false;message('A year has been reduced to the first dot. Name the phrase.')}}
})();
