(() => {
  const calendar=document.querySelector('#calendar'),calendarWrap=document.querySelector('#calendarWrap'),flyingPages=document.querySelector('#flyingPages'),year=document.querySelector('#year'),archiveNumber=document.querySelector('#archiveNumber'),status=document.querySelector('#status'),stage=document.querySelector('#stage'),answerLock=document.querySelector('#answerLock');
  const stages=[{to:2000,count:6},{to:1900,count:9},{to:1000,count:12},{to:100,count:15},{to:1,count:18},{to:'dot',count:22}];
  const hints=['Every loose page belongs to an earlier year.','The calendar is travelling backwards. Keep taking it towards the beginning.','What remains after the very first year has gone?'];
  let currentYear=2026,step=0,busy=false,hintIndex=0,soundOn=true,audioContext;
  function tone(frequency=150,duration=.045,volume=.018){if(!soundOn)return;try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type='triangle';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(volume,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+duration);oscillator.connect(gain).connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+duration)}catch(_){}}
  const tactile=pattern=>{if(navigator.vibrate)navigator.vibrate(pattern)};
  function pageValue(from,to,index,total){if(to==='dot')return Math.max(1,Math.round(from-(from-1)*(index+1)/total));const progress=(index+1)/total;return Math.max(to,Math.round(from-(from-to)*(progress*progress)))}
  function makeFlyingPage(value,index,total){const page=document.createElement('span');page.className='flying-page';page.textContent=value;const direction=index%2===0?1:-1;page.style.setProperty('--dx',`${direction*(42+Math.random()*65)}%`);page.style.setProperty('--dy',`${-45-Math.random()*55}%`);page.style.setProperty('--spin',`${direction*(12+Math.random()*24)}deg`);page.style.setProperty('--duration',`${620+Math.random()*190}ms`);flyingPages.append(page);setTimeout(()=>page.remove(),900)}
  function turnPages(){
    if(busy||step>=stages.length)return;busy=true;calendar.classList.add('busy');const config=stages[step],from=currentYear,interval=Math.max(38,92-step*9);status.textContent=step<2?'The years are falling away.':'The calendar is accelerating into the past.';
    for(let index=0;index<config.count;index++){setTimeout(()=>{const value=pageValue(from,config.to,index,config.count);makeFlyingPage(value,index,config.count);if(config.to!=='dot'){year.textContent=value;currentYear=value}tone(115+Math.random()*55);if(index%4===0)tactile(5)},index*interval)}
    const finish=config.count*interval+750;setTimeout(()=>{step++;calendar.classList.remove('busy');busy=false;archiveNumber.textContent=String(step+1).padStart(3,'0');if(config.to==='dot'){showDot()}else{year.textContent=config.to;currentYear=config.to;calendar.setAttribute('aria-label',`A calendar showing year ${config.to}. Turn its pages.`);status.textContent=config.to===1?'Only the first numbered year remains.':'Another layer of years waits beneath your hand.'}},finish)
  }
  function showDot(){busy=true;calendar.classList.add('final');year.textContent='•';calendar.setAttribute('aria-label','The final calendar page contains a single dot.');status.textContent='The years have run out. Only the final mark remains.';tone(310,.28,.03);tactile([12,35,28]);setTimeout(()=>{stage.classList.add('awaiting-answer');answerLock.hidden=false;document.querySelector('#answerInput').focus({preventScroll:true})},850)}
  calendar.addEventListener('click',turnPages);calendar.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();turnPages()}});
  document.querySelector('#answerForm').addEventListener('submit',event=>{event.preventDefault();const input=document.querySelector('#answerInput'),feedback=document.querySelector('#answerFeedback'),guess=input.value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(guess==='year dot'||guess==='the year dot'){document.querySelector('#solved').hidden=false;status.textContent='The last page has been solved.';tone(392,.38,.035);tactile([15,30,45])}else{feedback.textContent='Not quite. What did all those years finally become?';input.select();tone(72,.12,.012);tactile(15)}});
  const hint=document.querySelector('#hint'),hintText=document.querySelector('#hintText');function showHint(){hintText.textContent=hints[hintIndex];document.querySelector('#nextHint').hidden=hintIndex>=hints.length-1;hint.hidden=false}document.querySelector('#hintButton').addEventListener('click',showHint);document.querySelector('#nextHint').addEventListener('click',()=>{hintIndex=Math.min(hintIndex+1,hints.length-1);showHint()});document.querySelector('#hintClose').addEventListener('click',()=>{hint.hidden=true});document.querySelector('#soundButton').addEventListener('click',event=>{soundOn=!soundOn;event.currentTarget.textContent=soundOn?'Sound on':'Sound off';event.currentTarget.setAttribute('aria-pressed',String(soundOn));if(soundOn)tone(240)});document.querySelector('#resetButton').addEventListener('click',()=>location.reload());
  if(new URLSearchParams(location.search).get('preview')==='dot'){step=stages.length;busy=true;calendar.classList.add('final');year.textContent='•';stage.classList.add('awaiting-answer');answerLock.hidden=false;status.textContent='The years have run out. Only the final mark remains.'}
})();
