(function(){
'use strict';
const KEY='cluecanvas.case01.counterfeit.v1';
const app=document.getElementById('app'),live=document.getElementById('live');
const OBJECTS={
 ledger:{title:'Receiving ledger',type:'useful',body:'Paper stock received for the authenticated Morland print: rag paper, 24 × 32 cm. Old stock is recorded as having a faint CROWN / M watermark.'},
 lamp:{title:'Inspection lamp manual',type:'useful',body:'The handwritten service note says the useful ultraviolet calibration was logged by Security after the lamp was repaired. The dial itself has been reset.'},
 log:{title:'Shredded security log',type:'useful',body:'Four surviving strips each carry an event and one large handwritten digit. They are out of order.'},
 receipt:{title:'Coffee receipt',type:'decoy',body:'Two flat whites and a toasted sandwich, 7:46 PM. It proves someone was hungry, not which print is real.'},
 postcard:{title:'Postcard from Lyon',type:'decoy',body:'A cheerful note about rain, museums and terrible hotel pillows. No dates or marks match the shipment.'},
 paper:{title:'Discarded packing sheet',type:'decoy',body:'Modern foam wrap from this morning. Clean, generic and unrelated to the older paper stock.'}
};
const fragments=[
 {id:'a',digit:'6',time:'20:14',text:'Power interrupted during lamp service.'},
 {id:'b',digit:'5',time:'20:21',text:'Security camera restored seven minutes later.'},
 {id:'c',digit:'3',time:'20:02',text:'Courier seal photographed on arrival.'},
 {id:'d',digit:'·',time:'20:31',text:'Curator called to confirm the repaired lamp.'}
];
let s=load();
function fresh(){return{screen:'intro',seen:[],marked:[],order:['a','d','c','b'],timelineSolved:false,dial:330,lampSolved:false,selectedPrint:null,complete:false,hint:0,started:Date.now()}}
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return fresh()}}
function save(){localStorage.setItem(KEY,JSON.stringify(s))}
function say(t){live.textContent='';setTimeout(()=>live.textContent=t,20)}
function brand(){return '<div class="brand"><span class="mark">C</span><span><b>CLUE CANVAS</b><small>Case prototype</small></span></div>'}
function top(stage){return '<div class="top">'+brand()+'<span class="pill">'+stage+'</span></div>'}
function progress(n){let x='<div class="progress">';for(let i=1;i<=5;i++)x+='<span class="'+(i<n?'done':i===n?'active':'')+'"></span>';return x+'</div>'}
function button(label,action,cls=''){return '<button class="btn '+cls+'" data-action="'+action+'">'+label+'</button>'}
function render(){save(); if(s.screen==='intro')return intro(); if(s.screen==='room')return room(); if(s.screen==='timeline')return timeline(); if(s.screen==='lamp')return lamp(); if(s.screen==='prints')return prints(); if(s.screen==='done')return done()}
function intro(){app.innerHTML='<section class="screen dark">'+top('Case 01')+'<div class="case-hero"><span class="case-number">01</span><p class="eyebrow">The Counterfeit Room</p><h1>One print is real.<br>The room knows which.</h1><p class="lede">A private collection received four near-identical prints after a late-night transfer. By morning, their labels had been mixed. Your job is not to guess from appearances—it is to rebuild the chain of evidence and identify the authentic work.</p></div><div class="brief"><div class="brief-row"><span class="brief-icon">1</span><div><h3>Survey</h3><p class="lede">Inspect the room and decide which observations actually matter.</p></div></div><div class="brief-row"><span class="brief-icon">2</span><div><h3>Reconstruct</h3><p class="lede">Put damaged evidence back into a trustworthy order.</p></div></div><div class="brief-row"><span class="brief-icon">3</span><div><h3>Verify</h3><p class="lede">Use what you learned to test the four candidates.</p></div></div></div>'+button('Enter the room','start','teal')+'</section>'}
function room(){let evid=s.seen.map(id=>'<div class="evidence"><span>'+ (OBJECTS[id].type==='useful'?'◆':'◇') +'</span><div><strong>'+OBJECTS[id].title+'</strong><p>'+OBJECTS[id].body+'</p></div><span class="tag">'+(s.marked.includes(id)?'Marked':'Seen')+'</span></div>').join('');
let ready=s.seen.length===6&&s.marked.length===3;
app.innerHTML='<section class="screen">'+top('Stage 1 · Survey')+progress(1)+'<p class="eyebrow">Read the room</p><h2>Six objects. Only three matter.</h2><p class="lede">Inspect everything before deciding what belongs in the evidence chain. Mark exactly three items as relevant.</p><div class="card" style="margin-bottom:14px"><div class="stat"><span>Objects inspected</span><strong>'+s.seen.length+' / 6</strong></div><div class="stat"><span>Evidence marked</span><strong>'+s.marked.length+' / 3</strong></div></div><div class="room"><div class="scene-note">Tap objects to inspect them. Some are deliberately irrelevant.</div><div class="desk"></div>'+Object.keys(OBJECTS).map(id=>'<button class="object '+(s.seen.includes(id)?'seen':'')+'" data-object="'+id+'" data-id="'+id+'">'+OBJECTS[id].title+'</button>').join('')+'</div><div class="actions">'+button(ready?'Review marked evidence':'Complete the survey first','check-room',ready?'teal':'secondary')+button('Hint','hint','secondary')+'</div>'+(s.feedback?'<div class="feedback">'+s.feedback+'</div>':'')+(s.hint?'<div class="hint">'+roomHint()+'</div>':'')+(evid?'<div class="drawer">'+evid+'</div>':'')+'</section>'+modalIf()}
function modalIf(){if(!s.modal)return'';let o=OBJECTS[s.modal];return '<div class="modal"><div class="sheet"><button class="close" data-action="close">×</button><p class="eyebrow">'+(o.type==='useful'?'Potential evidence':'Room object')+'</p><h2>'+o.title+'</h2><div class="artifact">'+o.body+'</div><div class="actions"><button class="btn '+(s.marked.includes(s.modal)?'secondary':'teal')+'" data-action="toggle-mark">'+(s.marked.includes(s.modal)?'Unmark':'Mark as evidence')+'</button></div></div></div>'}
function roomHint(){return s.hint===1?'Start by asking which objects could help establish the paper, the inspection method, or a trustworthy sequence of events.':'Food and travel details may establish atmosphere, but they do not help authenticate the object.'}
function timeline(){let items=s.order.map((id,i)=>{let f=fragments.find(x=>x.id===id);return '<div class="fragment"><span class="digit">'+f.digit+'</span><div><b>'+f.time+'</b><div>'+f.text+'</div></div><div class="move"><button data-move="'+i+':-1">↑</button><button data-move="'+i+':1">↓</button></div></div>'}).join('');
app.innerHTML='<section class="screen">'+top('Stage 2 · Reconstruct')+progress(2)+'<p class="eyebrow">Security log</p><h2>Restore the sequence.</h2><p class="lede">The strips were recovered out of order. Arrange them from earliest to latest. The first three handwritten marks form the lamp calibration.</p><div class="timeline">'+items+'</div><div class="actions">'+button('Lock sequence','check-timeline','teal')+button('Hint','hint','secondary')+'</div>'+(s.feedback?'<div class="feedback '+(s.timelineSolved?'ok':'')+'">'+s.feedback+'</div>':'')+(s.hint?'<div class="hint">'+(s.hint===1?'Use the printed times. The handwritten symbols are the payload, not the ordering rule.':'The correct sequence begins 20:02 → 20:14 → 20:21.')+'</div>':'')+'</section>'}
function lamp(){app.innerHTML='<section class="screen dark">'+top('Stage 3 · Calibrate')+progress(3)+'<p class="eyebrow">Inspection lamp</p><h2>Set the wavelength.</h2><p class="lede">The dial was reset during servicing. Use the restored security sequence rather than guessing.</p><div class="dial-wrap"><div class="dial"><div class="dial-value"><span><b>'+s.dial+'</b>nm</span></div></div></div><div class="dial-controls"><button data-action="minus">−5</button><button data-action="plus">+5</button></div><div class="actions" style="margin-top:18px">'+button('Test calibration','check-lamp','teal')+button('Hint','hint','secondary')+'</div>'+(s.feedback?'<div class="feedback '+(s.lampSolved?'ok':'')+'">'+s.feedback+'</div>':'')+(s.hint?'<div class="hint">Read the first three handwritten marks in chronological order: they form a standard UV wavelength.</div>':'')+'</section>'}
function prints(){let defs=[
['A','CROWN / M watermark visible. Fibres stay dull. Ink fluoresces soft green.'],
['B','No watermark. Paper glows bright blue across the entire sheet.'],
['C','CROWN / M watermark visible. Paper glows bright blue; ink stays black.'],
['D','Watermark reads CROWN / N. Fibres stay dull. Ink fluoresces soft green.']
];
app.innerHTML='<section class="screen '+(s.lampSolved?'lamp-on':'')+'">'+top('Stage 4 · Verify')+progress(4)+'<p class="eyebrow">Candidate prints</p><h2>Inspect before you accuse.</h2><p class="lede">The calibrated lamp reveals what ordinary light hides. Compare each print against the receiving ledger and the expected behaviour of old rag paper.</p><div class="print-grid">'+defs.map(d=>'<button class="print '+(s.selectedPrint===d[0]?'selected':'')+'" data-print="'+d[0]+'"><b>Print '+d[0]+'</b><span class="uv"><strong>UV inspection</strong><br>'+d[1]+'</span></button>').join('')+'</div><div class="actions">'+button('Submit identification','check-print','teal')+button('Hint','hint','secondary')+'</div>'+(s.feedback?'<div class="feedback '+(s.complete?'ok':'')+'">'+s.feedback+'</div>':'')+(s.hint?'<div class="hint">'+(s.hint===1?'The authentic print must satisfy both the physical paper record and the UV behaviour. One correct property is not enough.':'Reject modern optical brighteners (bright blue paper), then compare the exact watermark letter.')+'</div>':'')+'</section>'}
function done(){let mins=Math.max(1,Math.round((Date.now()-s.started)/60000));app.innerHTML='<section class="screen dark">'+top('Case solved')+progress(5)+'<p class="eyebrow">Authentic: Print A</p><h1>You proved it.</h1><p class="lede">Print A is the only candidate that matches the recorded CROWN / M watermark, avoids the blue fluorescence of modern optical brighteners, and shows the expected soft-green ink response under the correctly reconstructed 365 nm inspection setting.</p><div class="debrief"><div class="card"><h3>Why the chain matters</h3><p class="lede">The ledger alone leaves A and C. The UV behaviour alone leaves A and D. Only the combined evidence isolates A.</p></div><div class="card"><div class="stat"><span>Stages completed</span><strong>4 linked deductions</strong></div><div class="stat"><span>Elapsed this run</span><strong>'+mins+' min</strong></div><div class="stat"><span>Hints used</span><strong>'+s.hintsUsed+'</strong></div></div></div><div class="actions">'+button('Replay case','reset','secondary')+'</div></section>'}
function inspect(id){if(!s.seen.includes(id))s.seen.push(id);s.modal=id;render()}
function handle(a){if(a==='start'){s.screen='room';s.started=Date.now()}else if(a==='close'){s.modal=null}else if(a==='toggle-mark'){let id=s.modal;if(s.marked.includes(id)){s.marked=s.marked.filter(x=>x!==id);s.feedback=''}else if(s.marked.length<3){s.marked.push(id);s.feedback=''}else{s.feedback='You can only mark three items. Unmark one before choosing another.';say(s.feedback)}}
else if(a==='check-room'){if(s.seen.length<6){s.feedback='Inspect all six room objects before committing.';say(s.feedback)}else if(['ledger','lamp','log'].every(x=>s.marked.includes(x))&&s.marked.length===3){s.screen='timeline';s.hint=0;s.feedback=''}else{s.feedback='That evidence set leaves you without a complete authentication chain. Reconsider what establishes material, method and sequence.';say(s.feedback)}}
else if(a==='hint'){s.hint=Math.min(2,(s.hint||0)+1);s.hintsUsed=(s.hintsUsed||0)+1}
else if(a==='check-timeline'){if(s.order.join('')==='cabd'){s.timelineSolved=true;s.feedback='Sequence restored. The first three handwritten marks read 3–6–5.';setTimeout(()=>{s.screen='lamp';s.hint=0;s.feedback='';render()},700)}else{s.timelineSolved=false;s.feedback='The sequence is not chronological yet. Use the printed times, not the handwritten marks.'}}
else if(a==='minus'){s.dial=Math.max(300,s.dial-5)}else if(a==='plus'){s.dial=Math.min(420,s.dial+5)}
else if(a==='check-lamp'){if(s.dial===365){s.lampSolved=true;s.feedback='Calibration accepted: 365 nm. The candidate prints can now be inspected.';setTimeout(()=>{s.screen='prints';s.hint=0;s.feedback='';render()},700)}else{s.lampSolved=false;s.feedback='The lamp powers on, but the response is inconsistent. Recheck the reconstructed digits.'}}
else if(a==='check-print'){if(!s.selectedPrint){s.feedback='Choose a print first.'}else if(s.selectedPrint==='A'){s.complete=true;s.feedback='Print A satisfies every independent constraint.';setTimeout(()=>{s.screen='done';render()},650)}else{s.complete=false;s.feedback='That print matches part of the evidence, but fails another independent test. Compare both watermark and UV behaviour.'}}
else if(a==='reset'){localStorage.removeItem(KEY);s=fresh()}render()}
document.addEventListener('click',e=>{let o=e.target.closest('[data-object]');if(o)return inspect(o.dataset.object);let p=e.target.closest('[data-print]');if(p){s.selectedPrint=p.dataset.print;return render()}let m=e.target.closest('[data-move]');if(m){let [i,d]=m.dataset.move.split(':').map(Number),j=i+d;if(j>=0&&j<s.order.length){let t=s.order[i];s.order[i]=s.order[j];s.order[j]=t;render()}return}let a=e.target.closest('[data-action]');if(a)handle(a.dataset.action)});
s.hintsUsed=s.hintsUsed||0;render();
})();