import type {Puzzle} from '../../../src/types'
export const puzzle: Puzzle={id:10001,contentVersion:'clue-logic-test-1',chapterId:'clue-logic-test',chapterOrder:1,answer:'a watched pot never boils',acceptedAnswers:['watched pot never boils','the watched pot never boils'],wordPattern:'1 7 3 5 5',difficulty:'Medium',difficultyScore:4,estimatedSolveSeconds:90,format:'motion',visualTemplate:'freeform',mechanics:['sequence'],prompt:'Watch the scene. Can you picture the phrase?',elements:[],clues:['Compare the water while you watch the pot with what happens when you turn away. A correct letter is now in place.','',''],region:'Global',unlock:{requiresPuzzleIds:[]},artwork:{version:2,creator:'Clue Canvas',source:'Original Before Service scene',licence:'Original scene; Three.js MIT',kind:'project-asset'},qa:{status:'Draft',testerResults:[]}}
export type Action={type:'letter';letter:string}|{type:'phrase';answer:string}|{type:'hint';id:string}
export type Round={lives:number;letters:string[];misses:string[];hints:string[];wrongPhrases:string[];status:'playing'|'won'|'lost'}
export const SAVE_KEY='cluecanvas.clueLogic.integration.v1'

export const sceneTitles=['Before Service','A Balancing Problem'] as const
export const puzzles: Puzzle[]=[puzzle,{...puzzle,id:10002,chapterOrder:2,answer:'keep the plates spinning',acceptedAnswers:['keep plates spinning','keeping the plates spinning','keeping plates spinning','spinning plates','keep all the plates spinning'],wordPattern:'4 3 6 8',difficultyScore:5,estimatedSolveSeconds:110,clues:['Watch what happens just before a plate is steadied. Every plate needs attention to stay moving. A correct letter is now in place.','',''],artwork:{...puzzle.artwork,source:'Original A Balancing Problem scene'}}]
export const sceneSaveKey=(index:number,base=SAVE_KEY)=>index===0?base:base+'.plates'
