import {useEffect,useLayoutEffect,useState} from 'react'
import {Button} from '../../../src/components/Button'
import {LogicChapter} from './LogicChapter'
import {CASE_KEY,CASE_ROUNDS,evidence,suspects,ingredients,restoreCase,submitDeduction,type CaseState} from './mystery-model'
type Page='brief'|'puzzle'|'discovery'|'evidence'|'deduction'
export function MysteryChapter({onExit}:{onExit:()=>void}){
 const [state,setState]=useState<CaseState>(()=>{try{return restoreCase(localStorage.getItem(CASE_KEY))}catch{return restoreCase(null)}})
 const [page,setPage]=useState<Page>('brief'),[active,setActive]=useState(0),[fresh,setFresh]=useState<string|null>(null),[person,setPerson]=useState(''),[ingredient,setIngredient]=useState(''),[feedback,setFeedback]=useState(''),[storageError,setStorageError]=useState(false)
 useEffect(()=>{try{localStorage.setItem(CASE_KEY,JSON.stringify({version:1,...state}))}catch{setStorageError(true)}},[state])
 useLayoutEffect(()=>{window.scrollTo({top:0,left:0,behavior:'instant'})},[page])
 const remaining=3-state.attempts.length,all=state.earned.length===5
 function investigate(){const next=evidence.findIndex(e=>!state.earned.includes(e.id));setFresh(null);if(next<0){setPage('deduction');return}setActive(next);setPage('puzzle')}
 function collect(id:string){if(!evidence.some(e=>e.id===id))return;setState(s=>s.earned.includes(id)?s:{...s,earned:[...s.earned,id]});setFresh(id)}
 function goBook(){setFresh(null);setPage('evidence')}
 const tools=<div className="case-toolbar"><button onClick={()=>setPage('brief')}>← Case overview</button><button onClick={goBook}>Casebook · {state.earned.length}/5</button></div>
 const storageNotice=storageError&&<p role="status">Your browser cannot save this investigation. Keep this page open to retain progress.</p>
 if(page==='puzzle')return <>{tools}{storageNotice}<LogicChapter key={active} initialScene={evidence[active].scene} singleScene puzzleOrdinal={active+1} puzzleTotal={5} onExit={()=>setPage('brief')} storageKey={CASE_ROUNDS} onComplete={({puzzleId})=>collect(puzzleId)} onChapterComplete={()=>{collect(evidence[active].id);setPage('discovery')}}/>{fresh&&<aside className="case-unlocked" role="status">Evidence secured: {evidence.find(e=>e.id===fresh)?.title}. Inspect this scene’s discovery after the puzzle.</aside>}</>
 return <main className="app-shell case-shell">{page==='brief'?<button className="text-button" onClick={onExit}>← Back to playtests</button>:tools}{storageNotice}
  {page==='brief'&&<><p className="kicker">CLUE LOGIC · CASE 01</p><h1>The opening-night mix-up</h1><p className="case-lead">The signature soup has been ruined. Five rooms hold the evidence. Work out <strong>who changed it</strong> and <strong>what they added</strong>.</p><div className="case-premise"><strong>The facts you can rely on</strong><p>Only these three staff members had access to the kitchen. No guests or delivery workers entered it. One of them added exactly one of the three ingredients below.</p></div><div className="case-suspects">{suspects.map(s=><article key={s.id}><span className="case-monogram" aria-hidden="true">{s.name[0]}</span><strong>{s.name}</strong><small>{s.role}</small></article>)}</div><p>Possible ingredients: <strong>salt, sugar or lemon juice.</strong></p><p>Solve each animated phrase to earn evidence. Casebook reading is free. Each phrase keeps its three lifelines; the final deduction has three attempts of its own.</p><Button onClick={investigate}>{state.solved?'Review the solved case':all?'Make your deduction':state.earned.length?'Continue investigation':'Begin investigation'}</Button><Button variant="secondary" onClick={goBook}>Open casebook · {state.earned.length}/5</Button><ol className="case-route">{evidence.map((e,i)=><li key={e.id}><span>{state.earned.includes(e.id)?'✓':'○'} Room {i+1}</span><button onClick={()=>{setActive(i);setFresh(null);setPage('puzzle')}}>{['The stove','The service counter','The dining room','The washing station','The prep table'][i]}</button><small>{state.earned.includes(e.id)?'Evidence collected':'Solve to investigate'}</small></li>)}</ol></>}
  {page==='discovery'&&state.earned.includes(evidence[active].id)&&<><p className="kicker">ROOM {active+1} · DISCOVERY</p><h1>Evidence secured</h1><article className="case-document is-new"><div className="case-document-meta"><span>{evidence[active].kind}</span><span>0{active+1}</span></div><h2>{evidence[active].title}</h2><p className="case-stamp">{evidence[active].mark}</p><p>{evidence[active].body}</p><p className="case-question">{evidence[active].question}</p></article><Button onClick={investigate}>{all?'Make your deduction':'Investigate the next room'}</Button><Button variant="secondary" onClick={goBook}>Review previous discoveries</Button></>}
  {page==='evidence'&&<><p className="kicker">YOUR CASEBOOK · FREE TO REVIEW</p><h1>Follow the evidence</h1><p>{state.earned.length} of 5 discoveries. Keep the time window, the staff movements and the packet number in mind.</p><div className="case-evidence-list">{evidence.map((e,i)=>state.earned.includes(e.id)?<article className={`case-document${fresh===e.id?' is-new':''}`} key={e.id}><div className="case-document-meta"><span>{e.kind}</span><span>0{i+1}</span></div><h2>{e.title}</h2><p className="case-stamp">{e.mark}</p><p>{e.body}</p><p className="case-question">{e.question}</p></article>:<article className="case-locked" key={e.id}><strong>Evidence 0{i+1} · Not discovered</strong><p>Solve the phrase in room {i+1} to inspect this item.</p><button onClick={()=>{setActive(i);setFresh(null);setPage('puzzle')}}>Investigate room {i+1} →</button></article>)}</div><Button onClick={investigate}>{all?'Make your deduction':'Investigate the next room'}</Button>{!state.earned.includes(evidence[active].id)&&<Button variant="secondary" onClick={()=>setPage('puzzle')}>Return to current puzzle</Button>}</>}
  {page==='deduction'&&!all&&<><h1>The case is still open</h1><p>Gather all five discoveries before making an accusation.</p><Button onClick={investigate}>Continue investigation</Button></>}
  {page==='deduction'&&all&&(state.solved?<><p className="kicker">CASE CLOSED</p><h1>A good intention.<br/>A very bad measure.</h1><p className="case-solution"><strong>Iris added sugar.</strong></p><ol className="case-reconstruction"><li>The tasting log limits the addition to 7:10–7:20.</li><li>Mara and Theo were in the dining room for that entire interval. Of the three people with access, only Iris had the opportunity.</li><li>The torn S17 packet connects the hidden rubbish to the soup pot.</li><li>The supplier’s docket identifies S17 as caster sugar.</li></ol><div className="case-premise"><strong>What happened next</strong><p>When shown the evidence, Iris admits she tried to soften the soup’s sharp flavour. She used the whole sachet instead of a pinch, then swept the empty wrapper out of sight. It was an embarrassed cover-up of a cooking mistake.</p><p>The recipe note explains the instruction; her admission confirms the motive. You did not need to guess her intentions to solve the case.</p></div><Button variant="secondary" onClick={goBook}>Review all evidence</Button><Button onClick={onExit}>Back to playtests</Button></>:<><p className="kicker">THE FINAL DEDUCTION</p><h1>Who changed the soup?</h1><p>Choose one person and one ingredient. Both must fit the evidence.</p><strong>{remaining} of 3 attempts remaining</strong>{remaining>0?<form className="case-deduction" onSubmit={e=>{e.preventDefault();const result=submitDeduction(state,person,ingredient);setState(result.state);setFeedback(result.message)}}><fieldset><legend>Who had the opportunity?</legend>{suspects.map(s=><label key={s.id}><input type="radio" name="person" value={s.id} checked={person===s.id} onChange={()=>setPerson(s.id)}/><span>{s.name}<small>{s.role}</small></span></label>)}</fieldset><fieldset><legend>What did they add?</legend>{ingredients.map(i=><label key={i.id}><input type="radio" name="ingredient" value={i.id} checked={ingredient===i.id} onChange={()=>setIngredient(i.id)}/>{i.name}</label>)}</fieldset><Button type="submit" disabled={!person||!ingredient}>Check my theory</Button></form>:<div className="case-premise"><h2>Time to rethink</h2><p>Your evidence is safe. Review the casebook before making another deduction.</p><Button onClick={()=>{setState(s=>({...s,attempts:[]}));setPerson('');setIngredient('');setFeedback('Three fresh attempts.')}}>Retry the deduction</Button></div>}<p role="status">{feedback}</p><Button variant="secondary" onClick={goBook}>Review evidence · free</Button></>)}
 </main>
}

import './mystery.css'
